name: Build Armbian for RockPi-4B+

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build-armbian:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            curl \
            unzip \
            wget \
            xz-utils

      - name: Install dependencies
        run: |
          sudo apt-get install -y \
            gcc \
            g++ \
            make \
            bc \
            bison \
            flex \
            libssl-dev \
            libncurses5-dev \
            libncursesw5-dev \
            qemu-user-static \
            debootstrap \
            binfmt-support \
            build-essential \
            u-boot-tools \
            device-tree-compiler

      - name: Clone Armbian build repository
        run: |
          git clone --depth 1 https://github.com/armbian/build.git

      - name: Configure build
        run: |
          cd build
          ./compile.sh EXPERT=yes \
            BOARD=rockpi-4bplus \
            BRANCH=current kernel\
            RELEASE=buster \
            BUILD_MINIMAL=yes
            KERNEL_CONFIGURE=no


      - name: Upload Armbian image
        uses: actions/upload-artifact@v3
        with:
          name: armbian-image
          path: |
            ./build/output/images/*.img
