name: Build Armbian
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

#name: Build Armbian Image
#on: [push]
#  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: armbian/build@main
      with:
        armbian_target: "build"  # Set to "build" for building an image [1, 5, 6]
        armbian_board: "rockpi-4bplus"  # Specify your target board [1, 6]
        armbian_release: "jammy"  # Specify the Armbian release version [1, 6]
        armbian_kernel_branch: "current"
        armbian_ui: "minimal"
