#from : https://github.com/armbian/os/blob/main/.github/workflows/complete-artifact-one-by-one.yml
#and
#from : https://github.com/melix/sunscan-backend/blob/cc/build-sunscan-os/.github/workflows/build-image.yml
#############################
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Determine version
        id: vars
        run: |
          # Get the tag, if any
          TAG=$(git describe --tags --exact-match 2>/dev/null || echo "")
          
          if [ -n "$TAG" ]; then
            echo "APP_VERSION=$TAG" >> $GITHUB_ENV
            echo "IMGFILENAME=sunscan_os_$TAG" >> $GITHUB_ENV
          else
            BRANCH=$(git rev-parse --abbrev-ref HEAD)
            COMMIT=$(git rev-parse --short HEAD)
            echo "APP_VERSION=${BRANCH}_${COMMIT}" >> $GITHUB_ENV
            echo "IMGFILENAME=sunscan_os_${BRANCH}_${COMMIT}" >> $GITHUB_ENV
          fi
      - run: |
          {
          mkdir -p pi-gen-sunscan/01-prepare-repo
          cat > pi-gen-sunscan/01-prepare-repo/00-run.sh <<-EOF
          #!/bin/bash
          git clone ${{ github.server_url }}/${{ github.repository }}.git --branch ${{ github.head_ref }} --depth 1 \${WORK_DIR}/tmp/repo
          
          EOF
          } &&
          chmod +x pi-gen-sunscan/01-prepare-repo/00-run.sh

      - uses: usimd/pi-gen-action@v1
        id: build
        with:
          compression: xz

          # Compression level to be used. From 0 to 9 (refer to the tool man page for more
          # information on this. Usually 0 is no compression but very fast, up to 9 with the
          # best compression but very slow).
          compression-level: 6

          # Enable SSH access to Pi.
          enable-ssh: 1

          export-last-stage-only: true

          # Comma or whitespace separated list of additional packages to install on host
          # before running pi-gen. Use this list to add any packages your custom stages may
          # require. Note that this is not affecting the final image. In order to add
          # additional packages, you need to add a respective 'XX-packages' file in your
          # custom stage.
          extra-host-dependencies: ''

          # Comma or whitespace separated list of additional modules to load on host before
          # running pi-gen. If your custom stage requires additional software or kernel
          # modules to be loaded, add them here. Note that this is not meant to configure
          # modules to be loaded in the target image.
          extra-host-modules: ''

          # Token to use for checking out pi-gen repo.
          github-token: ${{ github.token }}

          # Host name of the image.
          hostname: sunscan

          # Final image name.
          image-name: ${{ env.IMGFILENAME }}

          # Enabling this option will remove plenty of components from the GitHub Actions
          # runner that are not mandatory pre-requisites for a (vanilla) pi-gen build. This
          # shall increase the available disk space so that also large images can be
          # compiled on a free GHA runner (benchmark is the full image including a desktop
          # environment). If any packages are missing during the build consider adding them
          # to the `extra-host-dependencies` list.
          increase-runner-disk-size: false

          # Default keyboard keymap.
          keyboard-keymap: us

          # Default keyboard layout.
          keyboard-layout: English (US)

          # Default locale of the system image.
          locale: en_US.UTF-8

          # Password of the intial user account, locked if empty.
          password: 'sunscan'

          # Path where selected pi-gen ref will be checked out to. If the path does not yet
          # exist, it will be created (including its parents).
          pi-gen-dir: pi-gen

          # The release name to use in `/etc/issue.txt`. The default should only be used for
          # official Raspberry Pi builds.
          pi-gen-release: Raspberry Pi reference

          # GitHub repository to fetch pi-gen from, must be a fork from RPi-Distro/pi-gen.
          pi-gen-repository: RPi-Distro/pi-gen

          # Release version of pi-gen to use. This can both be a branch or tag name known in
          # the pi-gen repository.
          pi-gen-version: arm64

          # Setting to `1` will disable password authentication for SSH and enable public
          # key authentication. Note that if SSH is not enabled this will take effect when
          # SSH becomes enabled.
          pubkey-only-ssh: 0

          # The release version to build images against. Valid values are jessie, stretch,
          # buster, bullseye, bookworm, and testing.
          release: bookworm

          # List of stage name to execute in given order. Relative and absolute paths to
          # custom stage directories are allowed here. Note that by default pi-gen exports
          # images in stage2 (lite), stage4 and stage5. You probably want to hook in custom
          # stages before one of the exported stages. Otherwise, the action will make sure
          # any custom stage will include an image export directive.
          stage-list: stage0 stage1 stage2 ./pi-gen-sunscan

          # System timezone.
          timezone: Europe/Paris

          # Name of the initial user account.
          username: admin

          # Print all output from pi-gen.
          verbose-output: true
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.IMGFILENAME }}
          path: ${{ steps.build.outputs.image-path }}
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
            files: ${{ steps.build.outputs.image-path }}
##################
name: "Builds the Sunscan OS image - MattC"
on:
 # pull_request:
 # push:
 #   tags:
 #     - '*.*.*'
 #   branches:
 #     - main
  workflow_dispatch:
    inputs:

      armbian_target:
        type: choice
        description: 'Build'
        required: false
        options:
        - kernel
        - build
        default: 'build'

      armbian_kernel_branch:
        type: choice
        description: 'Kernel branch'
        options:
        - legacy
        - current
        - edge
        default: 'current'

      armbian_release:
        type: choice
        description: 'Userspace'
        options:
        - jammy
        - mantic
        - bookworm
        - trixie
        - sid
        default: 'jammy'

      armbian_ui:
        type: choice
        description: 'User interface (not all works)'
        options:
        - minimal
        - server
        - xfce
        - gnome
        - cinnamon
        - i3-wm
        - kde-plasma
        default: 'minimal'

      armbian_version:
        description: 'Version'
        required: false
        default: ''

      armbian_board:
        type: choice
        description: 'Board'
        options:
        - aml-a311d-cc
        - aml-s905d3-cc
        - armsom-aim7-io
        - armsom-cm5-io
        - armsom-cm5-rpi-cm4-io
        - armsom-sige1
        - armsom-sige3
        - armsom-sige5
        - armsom-sige7
        - armsom-w3
        - avaota-a1
        - bananapi
        - bananapicm4io
        - bananapim1plus
        - bananapim2plus
        - bananapim2pro
        - bananapim2s
        - bananapim2ultra
        - bananapim2zero
        - bananapim3
        - bananapim4zero
        - bananapim5
        - bananapim64
        - bananapim7
        - bananapipro
        - bananapir2
        - bananapir2pro
        - beaglev
        - bigtreetech-cb1
        - bigtreetech-cb2
        - cherryba-m1
        - clearfogbase
        - clearfogpro
        - clockworkpi-a06
        - cm3588-nas
        - coolpi-cm5
        - coolpi-genbook
        - core3566
        - cubieboard
        - cubieboard2
        - cubieboard4
        - cubietruck
        - cubox-i
        - cyber-aib-rk3588
        - dshanpi-r1
        - fine3399
        - firefly-itx-3588j
        - firefly-rk3399
        - fxblox-rk1
        - gateway-gz80x
        - helios4
        - helios64
        - hikey960
        - hinlink-h28k
        - hinlink-h66k
        - hinlink-h68k
        - hinlink-h88k
        - hinlink-hnas
        - hinlink-ht2
        - indiedroid-nova
        - inovato-quadra
        - jethubj100
        - jethubj200
        - jethubj80
        - jetson-nano
        - khadas-edge
        - khadas-edge2
        - khadas-vim1
        - khadas-vim1s
        - khadas-vim2
        - khadas-vim3
        - khadas-vim3l
        - khadas-vim4
        - lafrite
        - lckfb-taishanpi
        - leez-p710
        - lepotato
        - lime-a33
        - lime-a64
        - lime
        - lime2
        - longanpi-3h
        - longanpi-4b
        - lubancat2
        - luckfox-core3566
        - macchiatobin-doubleshot
        - mangopi-m28k
        - mba8mpxl-ras314
        - mba8mpxl
        - mekotronics-r58-minipc
        - mekotronics-r58x-4g
        - mekotronics-r58x-pro
        - mekotronics-r58x
        - melea1000
        - mixtile-blade3
        - mixtile-edge2
        - mk808c
        - mkspi
        - nanopct4
        - nanopct6-lts
        - nanopct6
        - nanopi-m6
        - nanopi-r1
        - nanopi-r1s-h5
        - nanopi-r2c
        - nanopi-r2s
        - nanopi-r4s
        - nanopi-r4se
        - nanopi-r5c
        - nanopi-r5s
        - nanopi-r6c
        - nanopi-r6s
        - nanopia64
        - nanopiair
        - nanopiduo
        - nanopiduo2
        - nanopik1plus
        - nanopik2-s905
        - nanopim4
        - nanopim4v2
        - nanopineo
        - nanopineo2
        - nanopineo2black
        - nanopineo3
        - nanopineo4
        - nanopineocore2
        - nanopineoplus2
        - odroidc1
        - odroidc2
        - odroidc4
        - odroidhc4
        - odroidm1
        - odroidn2
        - odroidn2l
        - odroidxu4
        - olimex-a20-olinuxino-micro
        - olimex-teres-a64
        - olinux-som-a13
        - onecloud
        - oneplus-kebab
        - orangepi-r1
        - orangepi-r1plus-lts
        - orangepi-r1plus
        - orangepi-rk3399
        - orangepi2
        - orangepi3-lts
        - orangepi3
        - orangepi3b
        - orangepi4-lts
        - orangepi4
        - orangepi5-max
        - orangepi5-plus
        - orangepi5
        - orangepi5pro
        - orangepilite
        - orangepilite2
        - orangepione
        - orangepioneplus
        - orangepipc
        - orangepipc2
        - orangepipcplus
        - orangepiplus
        - orangepiplus2e
        - orangepiprime
        - orangepiwin
        - orangepizero
        - orangepizero2
        - orangepizero2w
        - orangepizero3
        - orangepizeroplus
        - orangepizeroplus2-h3
        - orangepizeroplus2-h5
        - panther-x2
        - pcduino3
        - phytiumpi
        - pine64
        - pine64so
        - pinebook-a64
        - pinebook-pro
        - pinecube
        - pineh64-b
        - pineh64
        - pocketchip
        - qemu-uboot-arm64
        - qemu-uboot-x86
        - qemu-uefi-x86
        - quartz64a
        - quartz64b
        - radxa-e20c
        - radxa-e25
        - radxa-e52c
        - radxa-zero
        - radxa-zero2
        - radxa-zero3
        - recore
        - renegade
        - retro-lite-cm5
        - retroidpocket-rp5
        - retroidpocket-rpmini
        - rk3328-heltec
        - roc-rk3399-pc
        - rock-3a
        - rock-3c
        - rock-4se
        - rock-5-cm-rpi-cm4-io
        - rock-5-cmio
        - rock-5-itx
        - rock-5a
        - rock-5b-plus
        - rock-5b
        - rock-5c
        - rock-s0
        - rock64
        - rockpi-4a
        - rockpi-4b
        - rockpi-4bplus
        - rockpi-4c
        - rockpi-4cplus
        - rockpi-e
        - rockpi-n10
        - rockpi-s
        - rockpro64
        - rpi4b
        - rpi5b
        - sakurapi-rk3308b
        - sk-am62b
        - sk-am64b
        - sk-am68
        - sk-tda4vm
        - star64
        - station-m1
        - station-m2
        - station-m3
        - station-p1
        - station-p2
        - sweet-potato
        - thinkpad-x13s
        - tinker-edge-r
        - tinkerboard-2
        - tinkerboard
        - tritium-h3
        - tritium-h5
        - turing-rk1
        - udoo
        - uefi-arm64
        - uefi-riscv64
        - uefi-x86
        - unleashed
        - unmatched
        - visionfive
        - visionfive2
        - wdk2023
        - wsl2-arm64
        - wsl2-x86
        - xiaobao-nas
        - xiaomi-elish
        - youyeetoo-r1-v3
        - zeropi
        default: 'rockpi-4bplus'

jobs:
  build:
    name: "Build Armbian"
    runs-on: ubuntu-latest
    steps:
      - uses: armbian/build@v24.8.1
        with:
          #armbian_token:              "${{secrets.GITHUB_TOKEN}}"
          armbian_target:             "${{inputs.armbian_target}}"
          armbian_release:            "${{inputs.armbian_release}}"
          armbian_kernel_branch:      "${{inputs.armbian_kernel_branch}}"
          armbian_ui:                 "${{inputs.armbian_ui}}"
          armbian_board:              "${{inputs.armbian_board}}"
          armbian_release_title:     "Armbian SDK - MattC"
          armbian_release_body:       "Virtual images for x86 and arm64"
          armbian_pgp_key:            "${{secrets.GPG_KEY1}}"
          armbian_pgp_password:       "${{secrets.GPG_PASSPHRASE1}}"
