name: Build Armbian for RockPi-4B+

on:

  workflow_dispatch: # Allows manual triggering of the workflow


jobs:
  build-armbian:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone Armbian build repository
        run: |
          git clone --depth 1 https://github.com/armbian/build.git

      - name: Source level with build folder from armbian
        run : |
          ls -lha

      - name: Create userpatches and userpatches/overlay
        run : |
          # userpatches/overlay gets copied to tmp/overlay (under build)
          # want to make customize-image.sh, which will get run shortly before img is finalized
          # customize-image.sh is run from the root of the to-be-finalized image
          # at this point though we are still at the source level ...
          pwd
          ls -als

          # make folder tree. this will be visible in final image at tmp/overlay
          mkdir -p build/userpatches/overlay

          # copy a script to be run (this is for specific installs)
          cp -a custom-pkg-list build/userpatches/overlay

          # create customize-image.sh 'in line' and put in userpatches for build execution
          cat > build/userpatches/customize-image.sh <<-EOF
          #!bin/bash
          # anything done in here is in to-be-finalized image, starting at root (ie \)

          # fwiw, this is running as chroot, so dont need sudo
          apt list | grep git

          chmod +x tmp/overlay/00-install/00-install.sh
          ./tmp/overlay/00-install/00-install.sh
          EOF
          
      - name: Configure build
        run: |
          cd build
          ./compile.sh EXPERT=yes \
            BOARD=rockpi-4bplus \
            BRANCH=current \
            RELEASE=bookworm \
            BUILD_MINIMAL=yes \
            KERNEL_CONFIGURE=no \
            COMPRESS_OUTPUTIMAGE=xz \
            IMAGE_XZ_COMPRESSION_RATIO=6
            #ENABLE_SSH=yes \
            #HOSTNAME=sunscan_test \

      - name: Upload Armbian image
        uses: actions/upload-artifact@v4
        with:
          name: armbian-image
          path: ./output/images/*.xz

